# Generated by Django 4.2.6 on 2023-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="theme_picked",
            field=models.IntegerField(default=1),
        ),
    ]
