# Generated by Django 4.2.6 on 2024-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_jikanfavoriteanime_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jikanfavoriteanime",
            name="mal_id",
            field=models.IntegerField(unique=True),
        ),
    ]
