# Generated by Django 4.2.6 on 2024-02-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_todostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='core.todostatus'),
        ),
    ]
